name: Fly build and deploy

on:
  pull_request:
  push:
    branches:
    - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ vars.FLY_APP_NAME || secrets.FLY_APP_NAME }}
  FLY_BASE_APP_NAME: ${{ vars.FLY_APP_NAME || secrets.FLY_APP_NAME }}
  FLY_PRIMARY_REGION: ${{ vars.FLY_PRIMARY_REGION || secrets.FLY_PRIMARY_REGION }}
  FLY_SECONDARY_REGION: ${{ vars.FLY_SECONDARY_REGION || secrets.FLY_SECONDARY_REGION }}

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: markiannucci/flyctl-actions/setup-flyctl@main
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Dev Container task
        uses: devcontainers/ci@v0.2
        with:
          # Change this to point to your image name
          imageName: ghcr.io/markiannucci/headscale-on-fly-io-devcontainer
          # can't pass secrets --- see this issue https://github.com/devcontainers/ci/issues/40
          # # Change this to be your CI task/script
          # runCmd: |
          #   if [[ ${{ github.event_name }} == 'pull_request' ]]; then
          #     echo "FLY_APP_NAME=${FLY_APP_NAME}-${{ github.event.number }}" 
          #   fi
          #   echo "fly.toml:"
          #   envsubst < fly.template.toml | tee fly.toml      
          #   mix deps.get
          #   SECRET_KEY_BASE=$(mix phx.gen.secret)
          #   export SECRET_KEY_BASE
          #   flyctl apps create $FLY_APP_NAME
          #   flyctl secrets set SECRET_KEY_BASE=$SECRET_KEY_BASE
          #   flyctl postgres create -n $($FLY_APP_NAME)-db --volume-size 1 --vm-size shared-cpu-1x --region den --initial-cluster-size 2
          #   flyctl postgres attach --postgres-app $($FLY_APP_NAME)-db
          #   flyctl deploy
